server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: smartdelivery
          uri: http://localhost:8082
          predicates:
            - Path=/smartDeliveries/** 
        - id: smartpick
          uri: http://localhost:8083
          predicates:
            - Path=/picks/**
        - id: report
          uri: http://localhost:8084
          predicates:
            - Path= /reports/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: smartdelivery
          uri: http://smartdelivery:8080
          predicates:
            - Path=/smartDeliveries/** 
        - id: smartpick
          uri: http://smartpick:8080
          predicates:
            - Path=/picks/**
        - id: report
          uri: http://report:8080
          predicates:
            - Path= /reports/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
