apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 271153858532.dkr.ecr.ap-northeast-2.amazonaws.com/admin08/order:v2
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: "1"