apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpick
  labels:
    app: smartpick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartpick
  template:
    metadata:
      labels:
        app: smartpick
    spec:
      containers:
        - name: smartpick
          image: username/smartpick:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5