apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartdelivery
  labels:
    app: smartdelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartdelivery
  template:
    metadata:
      labels:
        app: smartdelivery
    spec:
      containers:
        - name: smartdelivery
          image: username/smartdelivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5